package httpapi

import (
	"context"
	"strings"
	"sync"
	"time"

	"github.com/BryantVanOrden/AgentFleet/backend/internal/connectors"
	"github.com/BryantVanOrden/AgentFleet/backend/internal/vault"
	"github.com/BryantVanOrden/AgentFleet/backend/pkg/protocol"
)

// peerReplyKind marks a message generated by this responder.
//
// It is what stops two idle agents talking forever: a reply never triggers
// another reply. Agents can still start a thread themselves mid-task with
// message_peer, and a human can always say something new.
const peerReplyKind = "reply"

// RunPeerResponder lets idle agents answer messages addressed to them.
//
// The agent loop only reads its inbox while a task is running (peerContext is
// built per turn), so an instance sitting idle never saw a broadcast and never
// answered one — which reads, correctly, as "nobody responded". This closes
// that gap: an idle instance still belongs to the fleet and should reply when
// spoken to.
//
// Instances that are mid-task are skipped on purpose. They will see the message
// in their next turn's FLEET block with the full context of what they are
// doing, which is a better answer than one composed out of band.
func (s *Server) RunPeerResponder(ctx context.Context) {
	const interval = 15 * time.Second

	// Last message answered per instance, so a reply is generated once. Held
	// in memory deliberately: on restart every instance re-reads its recent
	// inbox, and answering a stale message twice is cheaper than tracking
	// acknowledgements in the database.
	var mu sync.Mutex
	seen := map[string]time.Time{}

	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			instances, err := s.db.ListInstances(ctx)
			if err != nil {
				continue
			}
			for i := range instances {
				inst := instances[i]
				if inst.State != protocol.InstanceRunning {
					continue
				}
				if s.instanceIsBusy(ctx, inst.ID) {
					continue
				}

				mu.Lock()
				since := seen[inst.ID]
				mu.Unlock()

				msg, ok := s.nextUnanswered(ctx, inst.ID, since)
				if !ok {
					continue
				}

				mu.Lock()
				seen[inst.ID] = msg.CreatedAt
				mu.Unlock()

				s.replyToPeer(ctx, inst, msg)
			}
		}
	}
}

// instanceIsBusy reports whether a task is mid-flight on this instance. A busy
// agent is left alone: it will read the message in its next turn, with the
// context of what it is actually doing.
func (s *Server) instanceIsBusy(ctx context.Context, instanceID string) bool {
	tasks, err := s.db.ListTasks(ctx, instanceID, 20)
	if err != nil {
		// Unknown means leave it alone, rather than risk talking over a run.
		return true
	}
	for _, t := range tasks {
		switch t.State {
		case protocol.TaskRunning, protocol.TaskQueued, protocol.TaskAwaitingHuman:
			return true
		}
	}
	return false
}

// nextUnanswered finds the newest message this instance should answer.
//
// Only one per tick: answering a backlog all at once would flood the thread,
// and the newest message is the one worth responding to.
func (s *Server) nextUnanswered(ctx context.Context, instanceID string, since time.Time) (protocol.PeerMessage, bool) {
	msgs := vault.GlobalBus.ListMessages(ctx, instanceID, 10)

	var best protocol.PeerMessage
	found := false
	for _, m := range msgs {
		switch {
		case m.FromInstanceID == instanceID: // never answer yourself
		case m.Kind == peerReplyKind: // replies do not beget replies
		case !m.CreatedAt.After(since):
		case found && !m.CreatedAt.After(best.CreatedAt):
		default:
			best, found = m, true
		}
	}
	return best, found
}

func (s *Server) replyToPeer(ctx context.Context, inst protocol.Instance, msg protocol.PeerMessage) {
	ctx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()

	scope := "you directly"
	if msg.ToInstanceID == "broadcast" {
		scope = "the whole fleet"
	}

	resp, err := s.models.Complete(ctx, "", connectors.Request{
		System: "You are the agent \"" + inst.Name + "\" in a fleet of autonomous " +
			"desktop agents. Another member of the fleet, or the operator, has " +
			"messaged " + scope + ". You are idle right now — not working on a task. " +
			"Reply in one or two sentences: answer if you can, say plainly if you " +
			"cannot help, and say what you are able to do. Do not invent work you " +
			"have not done and do not claim to have started anything.",
		Messages: []connectors.Message{{
			Role: connectors.RoleUser,
			Text: msg.FromInstanceName + " said: " + msg.Content,
		}},
		// A reasoning model would spend the whole budget thinking and return
		// nothing; this is small talk between agents, not a plan.
		DisableThinking: true,
		MaxTokens:       220,
		Temperature:     0.3,
	})
	if err != nil {
		s.log.Warn("peer reply failed", "instance", inst.ID, "err", err)
		return
	}
	body := strings.TrimSpace(resp.Text)
	if body == "" {
		return
	}

	// Reply to the sender, or back to the fleet if it was a broadcast, so the
	// answer appears in the same conversation the question was asked in.
	to := msg.FromInstanceID
	if msg.ToInstanceID == "broadcast" || to == "" {
		to = "broadcast"
	}
	vault.GlobalBus.SendMessage(ctx, inst.ID, inst.Name, to, peerReplyKind, body, nil)
	s.log.Info("agent answered a peer message", "instance", inst.Name, "to", to)
}
