package httpapi

import (
	"context"
	"strings"
	"sync"
	"time"

	"github.com/BryantVanOrden/AgentFleet/backend/internal/connectors"
	"github.com/BryantVanOrden/AgentFleet/backend/internal/store"
	"github.com/BryantVanOrden/AgentFleet/backend/internal/vault"
	"github.com/BryantVanOrden/AgentFleet/backend/pkg/protocol"
)

// peerReplyKind marks a message generated by this responder.
//
// It is what stops two idle agents talking forever: a reply never triggers
// another reply. Agents can still start a thread themselves mid-task with
// message_peer, and a human can always say something new.
const peerReplyKind = "reply"

// peerSummaryKind marks a compaction summary. It stands in for messages rather
// than being one, so nobody answers it.
const peerSummaryKind = "summary"

// RunPeerResponder lets idle agents answer messages addressed to them.
//
// The agent loop only reads its inbox while a task is running (peerContext is
// built per turn), so an instance sitting idle never saw a broadcast and never
// answered one — which reads, correctly, as "nobody responded". This closes
// that gap: an idle instance still belongs to the fleet and should reply when
// spoken to.
//
// Instances that are mid-task are skipped on purpose. They will see the message
// in their next turn's FLEET block with the full context of what they are
// doing, which is a better answer than one composed out of band.
func (s *Server) RunPeerResponder(ctx context.Context) {
	const interval = 15 * time.Second

	// Last message answered per instance, so a reply is generated once. Held
	// in memory deliberately: on restart every instance re-reads its recent
	// inbox, and answering a stale message twice is cheaper than tracking
	// acknowledgements in the database.
	var mu sync.Mutex
	seen := map[string]time.Time{}

	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			instances, err := s.db.ListInstances(ctx)
			if err != nil {
				continue
			}
			for i := range instances {
				inst := instances[i]
				if inst.State != protocol.InstanceRunning {
					continue
				}
				if s.instanceIsBusy(ctx, inst.ID) {
					continue
				}

				mu.Lock()
				since := seen[inst.ID]
				mu.Unlock()

				msg, ok := s.nextUnanswered(ctx, inst.ID, since)
				if !ok {
					continue
				}

				mu.Lock()
				seen[inst.ID] = msg.CreatedAt
				mu.Unlock()

				s.replyToPeer(ctx, inst, msg)
			}
		}
	}
}

// instanceIsBusy reports whether a task is mid-flight on this instance. A busy
// agent is left alone: it will read the message in its next turn, with the
// context of what it is actually doing.
func (s *Server) instanceIsBusy(ctx context.Context, instanceID string) bool {
	tasks, err := s.db.ListTasks(ctx, instanceID, 20)
	if err != nil {
		// Unknown means leave it alone, rather than risk talking over a run.
		return true
	}
	for _, t := range tasks {
		switch t.State {
		case protocol.TaskRunning, protocol.TaskQueued, protocol.TaskAwaitingHuman:
			return true
		}
	}
	return false
}

// nextUnanswered finds the newest message this instance should answer.
//
// Only one per tick: answering a backlog all at once would flood the thread,
// and the newest message is the one worth responding to.
func (s *Server) nextUnanswered(ctx context.Context, instanceID string, since time.Time) (protocol.PeerMessage, bool) {
	msgs := vault.GlobalBus.ListMessages(ctx, instanceID, 10)

	// An agent's own most recent reply is a high-water mark that survives a
	// restart, unlike the in-memory one: having already replied after a
	// message is proof of having answered it. Without this every deploy made
	// the whole fleet answer the same question again, which is visible in any
	// channel that has been through a few.
	for _, m := range msgs {
		if m.FromInstanceID == instanceID && m.Kind == peerReplyKind &&
			m.CreatedAt.After(since) {
			since = m.CreatedAt
		}
	}

	var best protocol.PeerMessage
	found := false
	// Anything older than this is not worth answering. The high-water mark is
	// in memory, so every restart used to look like a fleet with a full inbox:
	// each agent answered the newest message again, however many hours old,
	// and a channel with three agents gained three replies to a question that
	// had been answered that morning. Verified against the live fleet, where
	// the last operator message was at 07:40 and the agents were still
	// re-answering it at 16:03.
	const freshEnough = 10 * time.Minute
	cutoff := time.Now().Add(-freshEnough)

	for _, m := range msgs {
		switch {
		case m.FromInstanceID == instanceID: // never answer yourself
		case !s.mayAnswer(instanceID, m):
			// Not in that room. A message the operator writes into a thread
			// between two other agents is addressed to the fleet, because a
			// message carries one recipient and a thread has several — so it
			// lands in every inbox. Without this check a third agent answered
			// into a pair thread it was not part of, which is exactly what a
			// private thread is supposed to prevent.
		case m.Kind == peerReplyKind: // replies do not beget replies
		case m.Kind == peerSummaryKind:
			// A summary is a record of what was said, not something said to
			// anyone. Compacting a thread used to make every agent chime in.
		case m.CreatedAt.Before(cutoff):
		case !m.CreatedAt.After(since):
		case found && !m.CreatedAt.After(best.CreatedAt):
		default:
			best, found = m, true
		}
	}
	return best, found
}

func (s *Server) replyToPeer(ctx context.Context, inst protocol.Instance, msg protocol.PeerMessage) {
	ctx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()

	scope := "you directly"
	if msg.ToInstanceID == "broadcast" {
		scope = "the whole fleet"
	}

	// "What is everyone up to" is the question this feature exists to answer,
	// and it cannot be answered from the message alone. Give the agent its own
	// recent history so the reply is a real status report rather than a
	// paraphrase of the question.
	status := s.recentActivity(ctx, inst)

	// Two different things get said in fleet comms, and answering both as a
	// status update was wrong.
	//
	// This was built to answer "what is everyone up to", so the prompt told
	// the agent to reply with a status update and never to claim it had
	// started anything. That is right for a question and useless for a
	// request: asked to work together and build something, four agents each
	// replied "I am currently idle and available" and nobody did anything.
	// The instruction not to claim work made it structurally incapable of
	// agreeing to any.
	//
	// So the agent decides which it was given, and says so in the first word.
	// A deterministic marker rather than a second classifier call: the reply
	// has to be generated anyway, and a round trip per agent per broadcast to
	// label it would cost more than the answer.
	resp, err := s.models.CompleteRole(ctx, inst.ProviderIDs, protocol.RoleChat,
		connectors.Request{
			System: "You are the agent \"" + inst.Name + "\" in a fleet of autonomous " +
				"desktop agents, reporting to your operator. " + scope +
				" was messaged.\n\n" + status + "\n\n" +
				"Decide first what you were sent.\n\n" +
				"If it ASKS YOU TO DO SOMETHING -- build, make, write, fix, find " +
				"out, work together on something -- reply starting with the single " +
				"word PLAN: followed by the specific part YOU will take on, in one " +
				"or two sentences. Pick a part that suits you and does not duplicate " +
				"what an obvious colleague would take; say what you will actually " +
				"produce. Do not ask for permission and do not ask which part to " +
				"take -- decide.\n\n" +
				"Otherwise it is a QUESTION about you or your machine. Reply in one " +
				"or two short sentences, in the first person, as a status update. " +
				"Ground every claim in the history above: if it says you have run " +
				"nothing, say you are idle and available. Never invent work, never " +
				"claim to have started something, and do not list your capabilities " +
				"unless you were asked what you can do.",
			Messages: []connectors.Message{{
				Role: connectors.RoleUser,
				Text: msg.FromInstanceName + " asked: " + msg.Content,
			}},
			// A reasoning model would spend the whole budget thinking and
			// return nothing.
			DisableThinking: true,
			MaxTokens:       260,
			Temperature:     0.3,
		})
	if err != nil {
		s.log.Warn("peer reply failed", "instance", inst.ID, "err", err)
		return
	}
	body := strings.TrimSpace(resp.Text)
	if body == "" {
		return
	}

	// Where the reply goes.
	//
	// An operator broadcast is answered in the group so every reply sits under
	// the question. Anything else — an agent asking another agent something —
	// is answered directly to the asker, which keeps agent chatter in its own
	// thread instead of filling the fleet channel with conversations the
	// operator did not start. The direct threads are still visible; they are
	// just not mixed in.
	to := msg.FromInstanceID
	if isOperator(msg) {
		// The operator has no instance ID for a reply to be addressed to. In a
		// two-agent thread the answer goes to the other agent, which is what
		// lets the pair carry on talking; anywhere else it goes to the fleet.
		if other, ok := vault.GlobalBus.OtherAgentMember(msg.ConversationID, inst.ID); ok {
			to = other
		} else {
			to = "broadcast"
		}
	}
	if to == "" {
		to = "broadcast"
	}

	// Which thread the answer belongs in is a separate question from who it is
	// addressed to, and conflating them leaked replies. An operator question in
	// a pair thread has no instance to address, so `to` falls back to
	// broadcast -- that must not drag the answer out of the thread it was
	// asked in and into the fleet channel.
	conv := msg.ConversationID
	if conv == "" {
		conv = protocol.BroadcastConversationID
	}
	vault.GlobalBus.SendMessageIn(ctx, conv, inst.ID, inst.Name, to, peerReplyKind, body, nil)
	s.log.Info("agent answered a peer message", "instance", inst.Name, "to", to, "conversation", conv)

	// A plan that nobody acts on is the bug this is fixing. If the agent
	// committed to a part, start it working on that part.
	if plan, ok := planFrom(body); ok && isOperator(msg) {
		s.startFromPlan(ctx, inst, msg, plan)
	}
}

// planMarker is how an agent says it was asked to do something rather than
// asked a question.
const planMarker = "PLAN:"

// planFrom pulls the committed part out of a reply, if there is one.
//
// Only when the agent opened with the marker. Matching "plan" anywhere in a
// sentence would turn "I have no plans today" into a task.
func planFrom(body string) (string, bool) {
	trimmed := strings.TrimSpace(body)
	if !strings.HasPrefix(strings.ToUpper(trimmed), planMarker) {
		return "", false
	}
	plan := strings.TrimSpace(trimmed[len(planMarker):])
	if plan == "" {
		return "", false
	}
	return plan, true
}

// startFromPlan turns an agent's stated part into a task it actually runs.
//
// Only for an operator's message: agents talking among themselves must not be
// able to start work on each other, or one bot's question becomes another
// bot's afternoon. And only when the agent is idle -- a broadcast arriving
// mid-task should not derail what it was already asked to do.
func (s *Server) startFromPlan(ctx context.Context, inst protocol.Instance, msg protocol.PeerMessage, plan string) {
	if inst.State != protocol.InstanceRunning {
		return
	}
	// One driver at a time, the same rule the task endpoint enforces: a
	// broadcast arriving mid-task must not derail what the agent was already
	// asked to do.
	existing, err := s.db.ListTasks(ctx, inst.ID, 20)
	if err != nil {
		return
	}
	for _, t := range existing {
		if t.State == protocol.TaskRunning || t.State == protocol.TaskAwaitingHuman ||
			t.State == protocol.TaskQueued {
			return
		}
	}

	task := &protocol.Task{
		ID:         store.NewID(),
		InstanceID: inst.ID,
		OwnerID:    msg.FromUserID,
		// Both halves: the request gives the goal its context, the plan is
		// what this particular agent said it would contribute.
		Goal: "The operator asked the fleet: " + msg.Content +
			"\n\nYour part, which you chose: " + plan +
			"\n\nDo that part. Publish what you produce to the shared work " +
			"catalog with publish_work so the rest of the fleet can build on " +
			"it, and read_work first to see what colleagues have already put " +
			"there. Message a peer if you need something from them.",
		State:     protocol.TaskQueued,
		MaxSteps:  s.cfg.MaxSteps,
		CreatedAt: time.Now().UTC(),
	}
	// Detached from the request that triggered it: the operator's message has
	// long been answered, and a task must not die with its HTTP context.
	bg := context.WithoutCancel(ctx)
	if err := s.db.CreateTask(bg, task); err != nil {
		s.log.Warn("could not queue work from a fleet plan", "instance", inst.Name, "err", err)
		return
	}
	if err := s.runner.Start(bg, task); err != nil {
		s.log.Warn("could not start work from a fleet plan", "instance", inst.Name, "err", err)
		return
	}
	s.log.Info("agent started work from a fleet request",
		"instance", inst.Name, "task", task.ID, "plan", clipLine(plan, 80))
}

func clipLine(s string, n int) string {
	s = strings.Join(strings.Fields(s), " ")
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

// mayAnswer reports whether this agent belongs in the message's thread.
//
// The broadcast channel and unfiled messages are open to everyone; a named
// conversation is not.
func (s *Server) mayAnswer(instanceID string, m protocol.PeerMessage) bool {
	conv := m.ConversationID
	if conv == "" || conv == protocol.BroadcastConversationID {
		return true
	}
	// A message addressed to this agent is for it whatever thread it sits in.
	if m.ToInstanceID == instanceID {
		return true
	}
	return vault.GlobalBus.IsMember(conv, instanceID)
}

// isOperator reports whether a message came from a human rather than an agent.
// Operator messages have no originating instance.
func isOperator(m protocol.PeerMessage) bool {
	return strings.TrimSpace(m.FromInstanceID) == ""
}

// recentActivity summarises what this agent has actually been doing, so a
// status reply is grounded in the record rather than improvised.
func (s *Server) recentActivity(ctx context.Context, inst protocol.Instance) string {
	tasks, err := s.db.ListTasks(ctx, inst.ID, 5)
	if err != nil || len(tasks) == 0 {
		return "YOUR HISTORY\nYou have not been given any work yet. You are idle and available."
	}

	var sb strings.Builder
	sb.WriteString("YOUR HISTORY (most recent first)\n")
	for i, t := range tasks {
		if i >= 3 {
			break
		}
		line := "- " + string(t.State) + ": " + trunc(t.Goal, 120)
		switch {
		case t.Result != "":
			line += " — outcome: " + trunc(t.Result, 160)
		case t.Error != "":
			line += " — failed: " + trunc(t.Error, 160)
		}
		sb.WriteString(line + "\n")
	}
	running := false
	for _, t := range tasks {
		if t.State == protocol.TaskRunning || t.State == protocol.TaskQueued {
			running = true
			break
		}
	}
	if running {
		sb.WriteString("Something of yours is still in flight.")
	} else {
		sb.WriteString("Nothing is running right now; you are free.")
	}
	return sb.String()
}

func trunc(s string, n int) string {
	s = strings.TrimSpace(s)
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
